### ISSUE TITLE
Ayles name appearing as アイルツ

### ISSUE THREAD

**Issue by furiousg4m3r** [pnvnd/Tales-of-Destiny-DC#299]
13822_55.txt
Patch 0.0.118
Even though it is translated in the file, in-game still appears in Japanese, アイルツ. 
![Screenshot 2021-02-12 165021](https://user-images.githubusercontent.com/77897370/107826219-84f00380-6d52-11eb-8ccc-e7f60753c138.png)

**Comment by dawnbomb** [comment]
Their name is probably shared with someone else with the same name, make sure to find all of 'him'

**Comment by pnvnd** [comment]
Fixed, will be pushed to next patch. SLPS
![image](https://user-images.githubusercontent.com/65086728/107859995-0d31df80-6e0b-11eb-9275-90d8279a6902.png)
