### ISSUE TITLE
Baruk's name in Japanese

### ISSUE THREAD

**Issue by furiousg4m3r** [pnvnd/Tales-of-Destiny-DC#336]
Baruk's name is still in Japanese even though it's translated in the file.
![image](https://user-images.githubusercontent.com/77897370/108266157-c1977280-7137-11eb-98ff-5430572233cc.png)

**Comment by pnvnd** [comment]
Revert Baruk's name back to the original. This will be reflect in SLPS file.

**Comment by furiousg4m3r** [comment]
Fixed.
